import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import LanguageSwitcher from "../components/LanguageSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <>
          <header className="flex justify-between items-center p-4 bg-gray-800 text-white">
            <LanguageSwitcher />
          </header>
          {children}
          <footer className="flex justify-center p-4 bg-gray-800 text-white">
            <p>© {new Date().getFullYear()} My App</p>
          </footer>
        </>
      </body>
    </html>
  );
}
